In [1]:
import numpy as np
import pandas as pd
import abcd_helper as abcd
from abcd_helper.config import DATA_DIR, PROCESSED_DATA_DIR

# Set plot styling
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="whitegrid", palette="muted")
pd.set_option("display.max_columns", 35)

# logging
import logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

In [2]:
df_convos = abcd.load_conversations()
logger.info(f"Loaded conversations table: {len(df_convos)} rows")

df_turns = abcd.load_turns()
logger.info(f"Loaded turns table: {len(df_turns)} rows")

extracted_slots_path = PROCESSED_DATA_DIR / "customer_slots_extracted_run_02.parquet"
logger.info(f"Loading NLP-extracted slots from {extracted_slots_path}")
df_extracted_slots = pd.read_parquet(extracted_slots_path)
logger.info(f"\tLoaded NLP-extracted slots table: {len(df_extracted_slots)} rows")

df_schemas = abcd.load_intent_slots(as_df=True)
logger.info(f"Loaded intent slots schema: {len(df_schemas)} rows")

INFO: Loaded conversations table: 10042 rows
INFO: Loaded turns table: 220983 rows
INFO: Loading NLP-extracted slots from /Users/ridho-akbar/Projects/data-science/projects/nlp-dialogue-state-tracking/data/processed/customer_slots_extracted_run_02.parquet
INFO: 	Loaded NLP-extracted slots table: 89372 rows
INFO: Loaded intent slots schema: 55 rows

In [3]:
from data_science.features.ast import extract_ast_features_batch
from data_science.features.dst import extract_dst_features_batch

In [4]:
from data_science.features.dst import extract_dst_features_batch
from data_science.features.ast import extract_ast_features_batch

df_dst_features = extract_dst_features_batch(
    df_convos=df_convos,
    df_slots=df_extracted_slots,
    df_schemas=df_schemas
)

df_ast_features = extract_ast_features_batch(
    df_convos=df_convos,
    df_turns=df_turns,
    df_slots=df_extracted_slots
)

In [7]:
df_dst_features.describe()

,convo_id,total_slots_disclosed,mandatory_slots_count,mandatory_slots_satisfied,mandatory_slot_coverage,all_mandatory_slots_filled,slot_filling_latency,upfront_slot_density,unused_slot_ratio,slot_repetition_count
count,10042.000000,10042.000000,10042.000000,10042.000000,10042.00000,10042.000000,10042.000000,10042.000000,10042.000000,10042.000000
mean,5390.756323,2.227943,1.349632,1.160526,0.89354,0.853615,8.391854,0.400126,0.273930,0.235212
std,3013.199552,1.863247,1.422200,1.345622,0.28186,0.353510,8.983253,0.483059,0.381126,0.648474
min,108.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2798.250000,1.000000,0.000000,0.000000,1.00000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,5403.500000,2.000000,1.000000,1.000000,1.00000,1.000000,7.000000,0.000000,0.000000,0.000000
75%,8005.750000,3.000000,2.000000,2.000000,1.00000,1.000000,14.000000,1.000000,0.500000,0.000000
max,10595.000000,10.000000,5.000000,5.000000,1.00000,1.000000,54.000000,1.000000,1.000000,10.000000

In [6]:
df_turns

,convo_id,turn_id,turn_count,split,speaker,text,text_delexed,flow,intent,next_step,action_name,action_values,slot_tags,char_len,word_len
0,3592,0,1,train,agent,Hi!,hi!,product_defect,return_size,retrieve_utterance,NaN,NaN,NaN,3,1
1,3592,1,2,train,agent,How can I help you?,how can i help you?,product_defect,return_size,retrieve_utterance,NaN,NaN,NaN,19,5
2,3592,2,3,train,customer,"Hi! I need to return an item, can you help me ...","hi! i need to return an item, can you help me ...",product_defect,return_size,NaN,NaN,NaN,NaN,56,13
3,3592,3,4,train,agent,"sure, may I have your name please?","sure, may i have your name please?",product_defect,return_size,retrieve_utterance,NaN,NaN,NaN,34,7
4,3592,4,5,train,customer,Crystal Minh,crystal minh,product_defect,return_size,NaN,NaN,NaN,NaN,12,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220978,2067,29,31,test,agent,You can go ahead and disregard that email now....,you can go ahead and disregard that email now....,shipping_issue,status,retrieve_utterance,NaN,NaN,NaN,98,19
220979,2067,30,32,test,customer,ok,ok,shipping_issue,status,NaN,NaN,NaN,NaN,2,1
220980,2067,31,33,test,customer,Thanks,thanks,shipping_issue,status,NaN,NaN,NaN,NaN,6,1
220981,2067,32,34,test,customer,bye then,bye then,shipping_issue,status,NaN,NaN,NaN,NaN,8,2
220982,2067,33,35,test,agent,You're welcome. Good bye,you're welcome. good bye,shipping_issue,status,retrieve_utterance,NaN,NaN,NaN,25,4